[package]
name = "oxiboy"
version = "0.1.0"
authors = ["Daniel Ribeiro <drgomesp@gmail.com>"]

[dependencies]
bitflags = "*"
clippy = {version = "0.0.21", optional = true}
failure = "*"

[features]
default = []
dev = ["clippy"]
